[[redirects]]
  from = "/images/test/:query"
  to = "/:query"
  status = 200

[[redirects]]
  from = "/images/:image"
  to = "https://res.cloudinary.com/dmaoqyvwt/image/fetch/:image"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200